### PR TITLE
Fix standalone adb , adb sideload and correct status bar offset

### PR DESCRIPTION
**Pull request by Yilliee**
Ever since mtp fix was added, adb when mtp is switched off as well as adb sideload stopped working. Adb when mtp was switched on worked and still works but now adb sideload as well as adb when mtp is switched off works. It's still a bit finicky as starting sideload or turning mtp on and off 2 times breaks adb and sideload until a further reboot to recovery, but just mtp works by default as before and now switching it off the first time makes sideload work. And yeah standalone adb still requires a restart of adbd

As for the 2nd commit, A51 has a 1080p screen and the original values of status bar offset which I assume were taken from a 1440p phone, leaves a lot of extra space. Setting the offset to 98 makes the top of status bar come much closer to the bottom of hole punch.

Anyways that's it for the long explaination if these commits.

### CODE REVIEW

**Comment by ghost** [comment]
Twrp.flags and recovery.fstab is different...

**Comment by Yilliee** [comment]
@manudinath Well they are supposed to be different. recovery.fstab is the one from stock recovery while twrp.fstab contains all the partitions and flags used by twrp. Some places name it twrp.flags but most commonly the file is named twrp.fstab.

**Comment by ghost** [comment]
No, you're wrong.

@Linux4 said "twrp.flags is the fstab that used fstab v1 format."

The reason we use twrp.flags is to declare needed flags in v1 format that normal recovery.fstab (v2) can't handle.

**Comment by ghost** [comment]
Even recovery.fstab is enough, but I don't see any tree that excludes twrp.flags. for newer devices ofc.

**Comment by ghost** [comment]
E.g. you may specific backup flags or display flags in twrp.flags.

**Comment by Yilliee** [comment]
I'm not sure what you even want to say now.
You started with "Twrp.flags and recovery.fstab is different..." well can you explain a bit what you wanted to point out there?
They should be same? I shouldn't use twrp.flags? Twrp.fstab should be named twrp.flags instead ?

**Comment by Yilliee** [comment]
Added firmware number/name to the commit of importing init files from stock recovery as suggested by @Synt4x93

**Comment by ghost** [comment]
Look at these entries:

`/boot				emmc	/dev/block/platform/13520000.ufs/by-name/boot		flags=backup=1;flashimg=1`

`/dev/block/platform/13520000.ufs/by-name/boot		/boot			emmc	defaults										recoveryonly`

The first one is from twrp.flags and the second is from recovery.fstab.

You may notice the differences of these 2 entries. **The backup flags.**

_Why these entries seperated into 2 fstabs?_

Because twrp.flags contains additional flags that recovery.fstab can't handle.

_What kind of flags?_

Like this, the backup flags. If you insert the backup flags to recovery.fstab, it can't handle it. Thus remains unbackupable (CMIIW).

You can know more by looking at @Linux4's [gta4xl tree](https://github.com/gta4xl/twrp_device_samsung_gta4xl/tree/android-10.0/recovery/root/system/etc).

**Comment by ghost** [comment]
`/external_sd			auto	/dev/block/mmcblk0p1 /dev/block/mmcblk0			flags=display="External SD";wipeingui;removable`

And this as well. From Tim's tree it is in twrp.flags, not recovery.fstab. That's it. recovery.fstab can't handle this.

BTW he used to insert that into recovery.fstab, and the TWRP can't detect MicroSD.

**Comment by Yilliee** [comment]
NH okay but what are you trying to point out here in pull request. The entries are separated here.

**Pull request merged**
